import React from 'react';
import { CVData, TemplateId } from '../types/cv';
import { t } from '../translations';

const Contact=({cv,dark=false}:{cv:CVData,dark?:boolean})=>{const p=cv.personal; const cls=dark?'text-slate-200':'text-slate-600';return <div className={`space-y-1 text-[10px] ${cls}`}>{p.email&&<div className="flex gap-2 items-center"><span aria-hidden="true">✉</span><span>{p.email}</span></div>}{p.phone&&<div className="flex gap-2 items-center"><span aria-hidden="true">☎</span><span>{p.phone}</span></div>}{p.location&&<div className="flex gap-2 items-center"><span aria-hidden="true">⌖</span><span>{p.location}</span></div>}{p.website&&<div className="flex gap-2 items-center"><span aria-hidden="true">↗</span><span>{p.website}</span></div>}{p.linkedin&&<div className="flex gap-2 items-center"><span className="font-semibold">in</span><span>{p.linkedin}</span></div>}{p.github&&<div className="flex gap-2 items-center"><span className="font-semibold">GH</span><span>{p.github}</span></div>}</div>}
const Section=({title,children,className=''}:{title:string,children:React.ReactNode,className?:string})=><section className={`mb-5 break-inside-avoid ${className}`}><h2 className="text-[11px] font-black uppercase tracking-[.18em] mb-2">{title}</h2>{children}</section>
const Timeline=({cv}:{cv:CVData})=><><Section title={t(cv.lang,'experience')}><div className="space-y-4">{cv.experience.map(x=><div key={x.id} className="break-inside-avoid"><div className="flex justify-between gap-4"><div className="font-bold text-[12px]">{x.jobTitle}</div><div className="text-[9px] text-slate-500">{x.startDate} — {x.current?'Present':x.endDate}</div></div><div className="text-[10px] font-semibold text-slate-600">{x.company}{x.location&&` · ${x.location}`}</div><p className="text-[10px] leading-5 text-slate-600 whitespace-pre-wrap mt-1">{x.description}</p></div>)}</div></Section><Section title={t(cv.lang,'education')}><div className="space-y-3">{cv.education.map(x=><div key={x.id} className="break-inside-avoid"><div className="font-bold text-[11px]">{x.degree}</div><div className="text-[10px] text-slate-600">{x.institution} · {x.startDate} — {x.endDate}</div><p className="text-[9px] text-slate-500 mt-1">{x.description}</p></div>)}</div></Section></>
const Side=({cv,dark=false}:{cv:CVData,dark?:boolean})=><><Contact cv={cv} dark={dark}/>{cv.skills.length>0&&<Section className="mt-6" title={t(cv.lang,'skills')}><div className="flex flex-wrap gap-1.5">{cv.skills.map(s=><span key={s.id} className={`px-2 py-1 rounded text-[9px] ${dark?'bg-white/10 text-white':'bg-slate-100 text-slate-700'}`}>{s.name}</span>)}</div></Section>}{cv.languages.length>0&&<Section title={t(cv.lang,'languages')}><div className="space-y-1">{cv.languages.map(l=><div key={l.id} className="text-[10px]"><b>{l.name}</b> · {l.level}</div>)}</div></Section>}{cv.certificates.length>0&&<Section title={t(cv.lang,'certificates')}><div className="space-y-2">{cv.certificates.map(c=><div key={c.id} className="text-[9px]"><b>{c.name}</b><div className={dark?'text-slate-300':'text-slate-500'}>{c.organization} · {c.date}</div></div>)}</div></Section>}</>
const Name=({cv,light=false}:{cv:CVData,light?:boolean})=><div><h1 className={`text-[28px] font-black tracking-tight ${light?'text-white':'text-slate-900'}`}>{cv.personal.firstName||'Your'} {cv.personal.lastName||'Name'}</h1><div className={`text-[12px] font-semibold ${light?'text-slate-200':'text-slate-500'}`}>{cv.personal.title||'Professional Title'}</div></div>
const SummaryProjects=({cv}:{cv:CVData})=><>{cv.personal.summary&&<Section title={t(cv.lang,'personal')}><p className="text-[10px] leading-5 text-slate-600">{cv.personal.summary}</p></Section>}{cv.projects.length>0&&<Section title={t(cv.lang,'projects')}><div className="space-y-3">{cv.projects.map(p=><div key={p.id}><div className="font-bold text-[11px]">{p.name}</div><div className="text-[9px] text-slate-500">{p.technologies}</div><p className="text-[10px] text-slate-600">{p.description}</p></div>)}</div></Section>}</>

export function CVTemplateModern({cv}:{cv:CVData}){return <div className="a4 text-slate-800"><div className="grid grid-cols-[65mm_1fr] min-h-[297mm]"><aside className="bg-slate-900 text-white p-8">{cv.personal.photo&&<img src={cv.personal.photo} className="w-28 h-28 object-cover rounded-2xl mb-6"/>}<Name cv={cv} light/><div className="mt-7"><Side cv={cv} dark/></div></aside><main className="p-10"><SummaryProjects cv={cv}/><Timeline cv={cv}/></main></div></div>}
export function CVTemplateProfessional({cv}:{cv:CVData}){return <div className="a4 p-10 text-slate-800"><header className="border-b-4 border-slate-800 pb-6 flex justify-between items-end gap-6"><Name cv={cv}/><Contact cv={cv}/></header><div className="grid grid-cols-[1fr_52mm] gap-10 mt-8"><main><SummaryProjects cv={cv}/><Timeline cv={cv}/></main><aside><Side cv={cv}/></aside></div></div>}
export function CVTemplateMinimal({cv}:{cv:CVData}){return <div className="a4 p-12 text-slate-800"><header className="text-center mb-8"><Name cv={cv}/><div className="flex justify-center mt-3"><Contact cv={cv}/></div></header><div className="border-t border-slate-300 pt-7"><SummaryProjects cv={cv}/><Timeline cv={cv}/><div className="grid grid-cols-2 gap-8"><Side cv={cv}/></div></div></div>}
export function CVTemplateExecutive({cv}:{cv:CVData}){return <div className="a4 text-slate-800"><header className="bg-[#273143] text-white px-12 py-10 flex justify-between"><Name cv={cv} light/><Contact cv={cv} dark/></header><div className="px-12 py-9 grid grid-cols-[1fr_50mm] gap-10"><main><SummaryProjects cv={cv}/><Timeline cv={cv}/></main><aside className="border-l pl-6"><Side cv={cv}/></aside></div></div>}
export function CVTemplateCreative({cv}:{cv:CVData}){return <div className="a4 p-0 text-slate-800"><div className="h-10 bg-amber-400"/><header className="p-10 pb-7 flex gap-7 items-center">{cv.personal.photo&&<img src={cv.personal.photo} className="w-24 h-24 object-cover rounded-full ring-8 ring-amber-50"/>}<div className="flex-1"><Name cv={cv}/><div className="mt-3"><Contact cv={cv}/></div></div></header><div className="px-10 grid grid-cols-[54mm_1fr] gap-9"><aside className="bg-amber-50 rounded-3xl p-6"><Side cv={cv}/></aside><main><SummaryProjects cv={cv}/><Timeline cv={cv}/></main></div></div>}
export function CVTemplateElegant({cv}:{cv:CVData}){return <div className="a4 p-12 text-[#292722]"><header className="mb-8"><div className="text-xs tracking-[.4em] uppercase text-stone-500">Curriculum Vitae</div><Name cv={cv}/><div className="h-px bg-stone-300 mt-5"/></header><div className="grid grid-cols-[1fr_54mm] gap-12"><main><SummaryProjects cv={cv}/><Timeline cv={cv}/></main><aside><Side cv={cv}/></aside></div></div>}
export const templateMap:Record<TemplateId,React.FC<{cv:CVData}>>={modern:CVTemplateModern,professional:CVTemplateProfessional,minimal:CVTemplateMinimal,executive:CVTemplateExecutive,creative:CVTemplateCreative,elegant:CVTemplateElegant};
